import { useRouter } from 'next/router'
import Head from 'next/head'
import styles from '../../../styles/Home.module.css'

const imagesUrl = [
  'https://avto.tatar/attachments/bcaab36f6631808ae3922a754ace642983fb7397/store/fill/1280/800/35e007d3641dff7cc578a831492246ef30368f1690a1d7ac3c8af2475579/Audi+A4+%D1%81%D0%B5%D0%B4%D0%B0%D0%BD.jpg',
  'https://a.d-cd.net/ZyBR8bvVXRgsfvz_9jy0qIUugX4-960.jpg',
  'https://i.infocar.ua/i/2/5872/115749/1024x.jpg'
]

const Image = (props: any) => {
  console.log('props', props)
  
  return (
    <div className={styles.container}>
       <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app 32" />
        <meta property="og:url" content="http://www.nytimes.com/2015/02/19/arts/international/when-great-minds-dont-think-alike.html" />
        <meta property="og:image" content="" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Image {props.id}
        </h1>
      </main>
    
    </div>
  )
}

export const getStaticPaths = () => {
  return {
    paths: [
      { params: { id: '0' } },
      { params: { id: '1' } },
      { params: { id: '2' } }
    ],
    fallback: true
  }
}

export const getStaticProps = (ctx: any) => {
  return {
    props: {
      imgPath: imagesUrl[Number(ctx.params.id)],
      id: ctx.params.id
    }
  }
}

export default  Image